name: inyecdiesel_eco
description: "Ecommerce app for InyecDiesel Eco."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Navigation
  go_router: ^13.2.0

  # Network
  dio: ^5.4.1
  internet_connection_checker: ^1.0.0+1

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2

  # UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  intl: ^0.18.1
  url_launcher: ^6.2.5  # For WhatsApp integration

  # Firebase (optional, you can add if needed)
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6

  # Charts for admin dashboard
  fl_chart: ^0.66.2

  # Form validation
  form_field_validator: ^1.1.0

  # Image handling
  image_picker: ^1.0.7

  # GetIt for dependency injection
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3  # For testing
  bloc_test: ^9.1.5  # For testing BLoC

flutter:
  uses-material-design: true

  # To add assets, uncomment this section
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # To add custom fonts, uncomment this section
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700